actions:
  pre:
    env_vars: ./misc/variables.sh
  post:
    i3-merge-modules: cat ~/.config/i3/modules/*.i3config > ~/.config/i3/config
    i3-restart: i3-msg restart

config:
  backup: false
  banner: false
  create: true
  dotpath: .
  default_actions:
    - env_vars
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.dotfiles

dotfiles:
  d_scripts:
    dst: ~/.scripts
    src: scripts
  f_profile:
    dst: ~/.profile
    src: misc/profile
  f_cronjobs:
    dst: ~/.cronjobs
    src: misc/.cronjobs
  f_Xresources:
    dst: ~/.Xresources
    src: configs/Xresources/.Xresources
  d_Xresources:
    dst: ~/.Xresources.d
    src: configs/Xresources/.Xresources.d
  f_zshrc:
    dst: ~/.zshrc
    src: configs/zsh/.zshrc
  f_zsh-theme:
    dst: ~/.oh-my-zsh/themes/disconnect.zsh-theme
    src: configs/zsh/disconnect.zsh-theme
  d_wal-templates:
    dst: ~/.config/wal/templates
    src: configs/wal
  f_compton:
    dst: ~/.config/compton/compton.conf
    src: configs/compton.conf
  f_rofi:
    dst: ~/.config/rofi/disconnect.rasi
    src: configs/rofi.rasi
  d_i3:
    dst: ~/.config/i3/modules
    src: configs/i3
    actions:
      - i3-merge-modules
      - i3-restart
  d_polybar:
    dst: ~/.config/polybar
    src: configs/polybar
  f_dunst:
    dst: ~/.config/dunst/dunstrc
    src: configs/dunstrc
profiles:
  disconnect:
    dotfiles:
    - f_profile
    - f_cronjobs
    - f_Xresources
    - d_Xresources
    - d_scripts
    - f_zshrc
    - f_zsh-theme
    - d_wal-templates
    - f_compton
    - f_rofi
    - d_i3
    - d_polybar
    - f_dunst
  work:
    dotfiles:
    - f_profile
    - f_cronjobs
    - f_Xresources
    - d_Xresources
    - d_scripts
    - f_zshrc
    - f_zsh-theme
    - d_wal-templates
    - f_compton
    - f_rofi
    - d_i3
    - d_polybar
    - f_dunst
