config:
  backup: true
  banner: true
  create: true
  dotpath: ~/.dotfiles
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  # f_font_hack:
  #   dst: ~/.local/share/fonts/
  #   src: ./fonts
  f_xinitrc:
    dst: ~/.xinitrc
    src: .xinitrc
  f_Xresources:
    dst: ~/.Xresources
    src: .Xresources
  d_Xresources:
    dst: ~/.Xresources.d
    src: .Xresources.d
  d_scripts:
    dst: ~/.scripts
    src: .scripts
  f_zshrc:
    dst: ~/.zshrc
    src: .zshrc
  f_zsh-theme:
    dst: ~/.oh-my-zsh/themes/disconnect.zsh-theme
    src: disconnect.zsh-theme
  d_wal-templates:
    dst: ~/.config/wal/templates
    src: wal_templates
  f_compton:
    dst: ~/.config/compton/compton.conf
    src: compton.conf
  f_rofi:
    dst: ~/.config/rofi/disconnect.rasi
    src: disconnect.rasi
  d_i3:
    dst: ~/.config/i3/modules
    src: i3config
  f_polybar:
    dst: ~/.config/polybar/config
    src: polybar
profiles:
  disconnect:
    dotfiles:
    - f_xinitrc
    - f_Xresources
    - d_Xresources
    - d_scripts
    - f_zshrc
    - f_zsh-theme
    - d_wal-templates
    - f_compton
    - f_rofi
    - d_i3
    - f_polybar
  work:
    dotfiles:
    - f_xinitrc
    - f_Xresources
    - d_Xresources
    - d_scripts
    - f_zshrc
    - f_zsh-theme
    - d_wal-templates
    - f_compton
    - f_rofi
    - d_i3
    - f_polybar
