config:
  backup: false
  banner: false
  create: true
  dotpath: dotfiles
  ignoreempty: false
  import_configs:
  - profiles.d/home.yaml
  - profiles.d/work.yaml
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.dotfiles

dotfiles:

profiles:
  disconnect:
    include:
    - home
  goldwin:
    include:
    - work
