config:
  backup: false
  banner: false
  create: true
  dotpath: .
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.dotfiles

dotfiles:
  # f_font_hack:
  #   dst: ~/.local/share/fonts/
  #   src: fonts/hack/*
  f_profile:
    dst: ~/.profile
    src: settings/profile
  f_cronjobs:
    dst: ~/.cronjobs
    src: settings/.cronjobs
  f_Xresources:
    dst: ~/.Xresources
    src: settings/Xresources/.Xresources
  d_Xresources:
    dst: ~/.Xresources.d
    src: settings/Xresources/.Xresources.d
  d_scripts:
    dst: ~/.scripts
    src: scripts
  f_zshrc:
    dst: ~/.zshrc
    src: settings/zsh/.zshrc
  f_zsh-theme:
    dst: ~/.oh-my-zsh/themes/disconnect.zsh-theme
    src: settings/zsh/disconnect.zsh-theme
  d_wal-templates:
    dst: ~/.config/wal/templates
    src: settings/wal
  f_compton:
    dst: ~/.config/compton/compton.conf
    src: configs/compton.conf
  f_rofi:
    dst: ~/.config/rofi/disconnect.rasi
    src: configs/rofi.rasi
  d_i3:
    dst: ~/.config/i3/modules
    src: configs/i3
  d_polybar:
    dst: ~/.config/polybar
    src: configs/polybar
profiles:
  disconnect:
    dotfiles:
    - f_profile
    - f_cronjobs
    - f_Xresources
    - d_Xresources
    - d_scripts
    - f_zshrc
    - f_zsh-theme
    - d_wal-templates
    - f_compton
    - f_rofi
    - d_i3
    - d_polybar
  work:
    dotfiles:
    - f_profile
    - f_cronjobs
    - f_Xresources
    - d_Xresources
    - d_scripts
    - f_zshrc
    - f_zsh-theme
    - d_wal-templates
    - f_compton
    - f_rofi
    - d_i3
    - d_polybar
