config:
  backup: false
  banner: false
  create: true
  dotpath: .
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.dotfiles

dotfiles:
  f_font_hack:
    # dst: ~/.local/share/fonts/
    dst: ~/test
    src: fonts/hack
    link: link
  f_lightdm:
    dst: /etc/lightdm/lightdm.conf
    src: configs/lightdm.conf
  f_lightdm-webkit2-greeter:
    dst: /etc/lightdm/lightdm-webkit2-greeter.conf
    src: configs/lightdm-webkit2-greeter.conf
  f_display-setup:
    dst: /usr/share/display-setup.sh
    src: scripts/display-setup.sh
profiles:
  disconnect:
    dotfiles:
    - f_font_hack
    - f_lightdm
    - f_lightdm-webkit2-greeter
    - f_display-setup
  work:
    dotfiles:
    - f_font_hack
    - f_lightdm
    - f_lightdm-webkit2-greeter
    - f_display-setup
