config:
  backup: false
  banner: false
  create: true
  dotpath: .
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.dotfiles

dotfiles:
  f_lightdm:
    dst: /etc/lightdm/lightdm.conf
    src: configs/lightdm
  f_lightdm-webkit2-greeter:
    dst: /etc/lightdm/lightdm-webkit2-greeter.conf
    src: configs/lightdm-webkit2-greeter
profiles:
  disconnect:
    dotfiles:
    - f_lightdm
    - f_lightdm-webkit2-greeter
  work:
    dotfiles:
    - f_lightdm
    - f_lightdm-webkit2-greeter
