################################################################################
##  Text                                                                      ##
################################################################################

font = Hack 9

# The spacing between lines. If the height is smaller than the font height, it
# will get raised to the font height.
line_height = 4

# Possible values are:
# full: Allow a small subset of html markup in notifications:
#        <b>bold</b>
#        <i>italic</i>
#        <s>strikethrough</s>
#        <u>underline</u>
#
#        For a complete reference see
#        <https://developer.gnome.org/pango/stable/pango-Markup.html>.
#
# strip: This setting is provided for compatibility with some broken clients
#        that send markup even though it's not enabled on the server. Dunst will
#        try to strip the markup but the parsing is simplistic so using this
#        option outside of matching rules for specific applications *IS GREATLY
#        DISCOURAGED*.
#
# no:    Disable markup parsing, incoming notifications will be treated as plain
#        text. Dunst will not advertise that it has the body-markup capability
#        if this is set as a global setting.
#
# It's important to note that markup inside the format option will be parsed
# regardless of what this is set to.
markup = full

# The format of the message. Possible variables are:
#   %a  appname
#   %s  summary
#   %b  body
#   %i  iconname (including its path)
#   %I  iconname (without its path)
#   %p  progress value if set ([  0%] to [100%]) or nothing
#   %n  progress value if set without any extra characters
#   %%  Literal %
# Markup is allowed
format = "<b>%s</b>\n%b"

# Alignment of message text.
# Possible values are "left", "center" and "right".
# (values: [top/center/bottom], default: center)
alignment = left

# Defines how the text and icon should be aligned vertically within the
# notification. If icons are disabled, this option has no effect.
vertical_alignment = top

# Show age of message if message is older than show_age_threshold seconds.
# Set to -1 to disable.
show_age_threshold = -1

# Split notifications into multiple lines if they don't fit into geometry.
word_wrap = no

# When word_wrap is set to no, specify where to make an ellipsis in long lines.
# Possible values are "start", "middle" and "end".
ellipsize = middle

# Ignore newlines '\n' in notifications.
ignore_newline = no

# Stack together notifications with the same content
stack_duplicates = true

# Hide the count of stacked notifications with the same content
hide_duplicate_count = false

# Display indicators for URLs (U) and actions (A).
show_indicators = yes
